### ISSUE TITLE
Feature Request : Dossier dans lequel se place le ssh_chroot

### ISSUE THREAD

**Issue by tomdereub** [maniackcrudelis/ssh_chroot#4]
Est-ce qu'il serait possible de définir un chemin lors de l'installation pour l'emplacement du dossier ? Je voudrais pouvoir mettre à disposition un espace sur un disque dur externe, qui n'est pas le disque sur lequel yunohost est installé.

**Comment by maniackcrudelis** [comment]
Tu peux déjà le faire
https://github.com/maniackcrudelis/ssh_chroot/blob/master/chroot_manager.sh#L51-L52

**Comment by tomdereub** [comment]
Ok, par contre on l'utilise comment ? C'est une nouvelle commande ?

**Comment by tomdereub** [comment]
Alors, j'ai trouvé la commande dans /home/yunohost.app/ssh_chroot_directories. Par contre, j'ai essayé de créer un utilisateur en spécifiant un dossier comme ça : 
`./chroot_manager adduser -n user -p password -d /media/DD2T/Sauvegardes/ssh_chroot -q 100G`
Et quand je me connecte en ssh avec cet utilisateur, il a accès à tout le serveur ! Donc le -d n'a pas l'air d'avoir marché...
et en fait quand je veux supprimer cet utilisateur avec chroot_manager, il me dit : "The user user isn't in a chroot."

**Comment by maniackcrudelis** [comment]
Est-ce que tu as un log de la commande ?

La mise en place effective de l'isolation de l'user se trouve dans la config ssh, tu peux regarder à la fin de /etc/ssh/sshd_config, tu devrais y trouver un paragraphe pour cet user.

**Comment by tomdereub** [comment]
Je n'ai pas de paragraphe dans /etc/ssh/sshd_config.
Voici ce que me retourne la commande de création d'un utilisateur : 
```
root@machine:/home/yunohost.app/ssh_chroot_directories# ./chroot_manager adduser -n user -p password -d /media/DD2T/Sauvegardes/ssh_chroot -q 100G
Create the user sauvugouser.
quotatool: using uid sauvugouser
quotatool: setting block limit
quotatool: setting hard limit to 100G
quotatool: using filesystem /dev/sdb1
quotatool: user 'sauvugouser' has uid 987
quotatool: filesystem /dev/sdb1 has device node /dev/sdb1
quotatool: Error while detecting kernel quota version: Function not implemented
```

**Comment by maniackcrudelis** [comment]
> "quotatool: Error while detecting kernel quota version: Function not implemented"

La commande quota échoue et stoppe le script.
Je vais voir la nécessité de garder l'option qui arrête le script en cas d'erreur.
En attendant, tu peux toujours tenter sans quota.

**Comment by maniackcrudelis** [comment]
J'ai finalement gardé cette sécurité, sauf pour deluser (https://github.com/maniackcrudelis/ssh_chroot/commit/49c53c542fc90216791b8e08a5410889ce31d37d).

Peux-tu me donner plus d'informations sur ton système ? En particulier l'architecture et le type de machine.
Pour le moment, sauf à comprendre pourquoi quotatool ne fonctionne pas chez toi, tu n'as d'autres options que de ne pas fixer de quotas.

**Comment by tomdereub** [comment]
C'est un pc portable en 64 bits, avec Yunohost 2.7.12.
Par contre, c'est dommage de ne pas supprimer le user créé si le script se stoppe, parce que là ça lui donnait un accès root à tout le serveur...
Sans fixer de quota ça a l'air de marcher, mais je n'arrive pas à me connecter en ssh avec le nouveau user. Est-ce qu'il y a quelque chose à ajouter lié au dossier en question ? Je mets le user, et quand je tape le mot de passe, j'ai : "packet_write_wait : Connection to ...IP... port ****: Broken pipe.

**Comment by maniackcrudelis** [comment]
Lorsque que le script est utilisé sans l'app YunoHost, il n'y a pas de gestion de trap. Mais soit, celà pourrait en effet être ajouté.

Tu te connectes comment ? Broken pipe c'est plus souvent une erreur côté client.

**Comment by tomdereub** [comment]
Je fais : 
`ssh user@domaine.tld -p monport`
Puis je rentre le mot de passe.
Je suis sur le salon de support, si tu veux qu'on essaie d'avancer de façon un peu plus rapide.

**Comment by tomdereub** [comment]
Conclusion : mon disque externe est en ntfs, c'est pour ça que ça foire. En réessayant sur un disque en ext4 ça fonctionne bien.
Merci !
